import {registerSheet} from 'react-native-actions-sheet';
import LoginActionsSheet from '../components/LoginActionsSheet';
import RegisterActionsSheet from '../components/RegisterActionsSheets';
import ForgotPasswordActionsSheet from '../components/ForgotpasswordActionSheet';
import EventCardActionsSheet from '../components/EventCardActionSheet';
registerSheet('login-sheet', LoginActionsSheet);
registerSheet('register-sheet', RegisterActionsSheet);
registerSheet('forgot-password-sheet', ForgotPasswordActionsSheet);
registerSheet('eventCard-sheet', EventCardActionsSheet);
export {};
